name: Build and Deploy Recommendation Service to AKS

on:
    push:
        branches:
            - main
            - github-workflow
        paths:
            - 'microservices/recommendation-service-python/**'

jobs:
    build-and-deploy-recommendation-service:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Azure Login
            uses: azure/login@v1
            with:
              creds: ${{ secrets.AZURE_CREDENTIALS }}

          - name: Build and push recommendation-service image to ACR
            run: |
              az acr build --registry tahcacr.azurecr.io --image recommendation-service:1.0.0 --image recommendation-service:latest -f microservices/recommendation-service-python/Dockerfile .

          - name: Set up kubectl
            uses: azure/setup-kubectl@v1
            with:
              version: 'latest'

          - name: Get AKS credentials
            run: az aks get-credentials --resource-group rg_moh_sulaeman --name aks-dev-test --admin

          - name: Deploy recommendation service to AKS
            run: kubectl apply -f microservices/recommendation-service-python/deploy-recommendation-service.yaml