name: Deploy MySQL to AKS

on:
  push:
    branches:
      - main
    paths:
      - 'monolith/mysql-deployment.yaml'
      - '.github/workflows/deploy-mysql.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'monolith/mysql-deployment.yaml'
      - '.github/workflows/deploy-mysql.yml'

jobs:
  deploy-mysql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Use kubelogin
      uses: azure/use-kubelogin@v1
      with:
        version: 'v0.0.10'

    - name: Get AKS credentials
      run: az aks get-credentials --resource-group rg_moh_sulaeman --name aks-dev-test

    - name: Deploy MySQL to AKS
      run: kubectl apply -f monolith/mysql-deployment.yaml