name: Build and Deploy Recommendation Service to AKS

on:
    push:
        branches:
            - main
        paths:
            - 'microservices/recommendation-service-python/**'
            - '.github/workflows/deploy-recommendation-service.yml'
    pull_request:
        branches:
            - main
        paths:
            - 'microservices/recommendation-service-python/**'
            - '.github/workflows/deploy-recommendation-service.yml'

jobs:
    build-and-deploy-recommendation-service:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Azure Login
            uses: azure/login@v1
            with:
              creds: ${{ secrets.AZURE_CREDENTIALS }}

          - name: Build and push recommendation-service image to ACR
            working-directory: microservices/recommendation-service-python
            run: |
              az acr build --registry tahcacr.azurecr.io --image recommendation-service:1.0.0 --image recommendation-service:latest -f Dockerfile .

          - name: Set up kubectl
            uses: azure/setup-kubectl@v1
            with:
              version: 'latest'

        #   - name: Install kubelogin
        #     run: |
        #         sudo az aks install-cli
        #         sudo apt-get update
        #         sudo apt-get install -y kubelogin

          - name: Get AKS credentials
            run: az aks get-credentials --resource-group rg_moh_sulaeman --name aks-dev-test

          - name: Deploy recommendation service to AKS
            run: kubectl apply -f microservices/recommendation-service-python/deploy-recommendation-service.yaml